# code modified from
#    https://github.com/bochinski/iou-tracker/blob/master/viou_tracker.py
#
from collections import OrderedDict
from dataclasses import dataclass, field
import numpy as np
from lapsolver import solve_dense

from videosys.ingestion.data import ObjectTrackingResult
from videosys.ingestion.base import Operator
from videosys.ingestion import fields
from .lib.vis_tracker import VisTracker
from .utils import iou

@dataclass
class VIOUTracklet:
    uid: int
    start_frame: int
    bboxes: list = field(default_factory=list)
    max_score: float = 0
    label: int = 0
    ttl: int = 0
    count: int = 1
    visual_tracker: object = None
    payload: object = None

    def __getattr__(self, attr):
        if attr == 'bbox':
            return None if len(self.bboxes) == 0 else self.bboxes[-1]
        raise AttributeError()

def viou_tracklet_to_result(tracklet):
    if tracklet.payload is not None:
        return ObjectTrackingResult(tracklet.uid, tracklet.label, tracklet.bbox, 
            tracklet.payload.confidence, tracklet.payload)
    else:
        return ObjectTrackingResult(tracklet.uid, tracklet.label, tracklet.bbox, -1)

def associate(tracks, detections, sigma_iou):
    """ perform association between tracks and detections in a frame.
    Args:
        tracks (list): input tracks
        detections (list): input detections
        sigma_iou (float): minimum intersection-over-union of a valid association
    Returns:
        (tuple): tuple containing:
        track_ids (numpy.array): 1D array with indexes of the tracks
        det_ids (numpy.array): 1D array of the associated indexes of the detections
    """
    costs = np.empty(shape=(len(tracks), len(detections)), dtype=np.float32)
    for row, track in enumerate(tracks):
        for col, detection in enumerate(detections):
            costs[row, col] = 1 - iou(track.bbox, detection.bbox)

    np.nan_to_num(costs)
    costs[costs > 1 - sigma_iou] = np.nan
    track_ids, det_ids = solve_dense(costs)
    return track_ids, det_ids

class VIOUTracker:
    """
    track object based on IOU and visual features.
    """

    def __init__(self, min_det_confidence, iou_threshold, window_size, 
        tracker_type=None, keep_upper_height_ratio=1.):
        """ V-IOU Tracker.
        See "Extending IOU Based Multi-Object Tracking by Visual Information by 
            E. Bochinski, T. Senst, T. Sikora" for more information.
        Args:
            frames_path (str): path to ALL frames.
                string must contain a placeholder like {:07d} to be replaced with the frame numbers.
            detections (list): list of detections per frame, usually generated by util.load_mot
            sigma_l (float): low detection threshold.
            sigma_h (float): high detection threshold.
            sigma_iou (float): IOU threshold.
            t_min (float): minimum track length in frames.
            ttl (float): maximum number of frames to perform visual tracking.
                        this can fill 'gaps' of up to 2*ttl frames (ttl times forward and backward).
            tracker_type (str): name of the visual tracker to use. see VisTracker for more details.
            keep_upper_height_ratio (float): float between 0.0 and 1.0 
                that determines the ratio of height of the object to track
                to the total height of the object used for visual tracking.
        Returns:
            list: list of tracks.
        """
        self.min_det_confidence = min_det_confidence
        self.iou_threshold = iou_threshold
        self.window_size = window_size
        self.tracker_type = tracker_type
        self.keep_upper_height_ratio = keep_upper_height_ratio
        if tracker_type == 'NONE':
            assert window_size == 1, \
                "window size should not be larger than 1 if no visual tracker is selected"
        self.__frame_buffer = []
        self.tracks_active = []
        self.tracks_extendable = []
        self.frame_num = 0
        self.next_id = 1

    def __new_tracklet(self, det):
        tracklet = VIOUTracklet(self.next_id, self.frame_num, [det.bbox], det.confidence,
            det.label, self.window_size, 1, None, det)
        self.next_id += 1
        return tracklet
    
    def update(self, frame, detection):
        self.__frame_buffer.append(frame)
        if len(self.__frame_buffer) > self.window_size + 1:
            self.__frame_buffer.pop(0)
        
        dets = [det for det in detection if det.confidence >= self.min_det_confidence]
        
        track_ids, det_ids = associate(self.tracks_active, dets, self.iou_threshold)

        updated_tracks = []
        for track_id, det_id in zip(track_ids, det_ids):
            tracklet = self.tracks_active[track_id]
            det = dets[det_id]
            # update tracklet.
            tracklet.bboxes.append(det.bbox)
            tracklet.max_score = max(tracklet.max_score, det.confidence)
            tracklet.payload = det
            tracklet.count += 1

            if tracklet.ttl != self.window_size:
                tracklet.ttl = self.window_size
                tracklet.visual_tracker = None
            updated_tracks.append(tracklet)
        
        tracks_not_updated = [self.tracks_active[idx] for idx in 
            set(range(len(self.tracks_active))).difference(set(track_ids))]

        for tracklet in tracks_not_updated:
            if tracklet.ttl > 0:
                if tracklet.ttl == self.window_size:
                    # init visual tracker
                    tracklet.visual_tracker = VisTracker(self.tracker_type, 
                        tracklet.bbox, self.__frame_buffer[-2], self.keep_upper_height_ratio)
                ok, bbox = tracklet.visual_tracker.update(frame)
                if not ok:
                    # visual update failed, track can still be extended
                    self.tracks_extendable.append(tracklet)
                    continue

                tracklet.ttl -= 1
                tracklet.bboxes.append(bbox)
                updated_tracks.append(tracklet)
            else:
                self.tracks_extendable.append(tracklet)
        
        # update the list of extendable tracks. tracks that are too old are moved to 
        # the finished_tracks. this should not be necessary but may improve the performance
        # for large numbers of tracks (eg. for mot19)
        tracks_extendable_updated = []
        for tracklet in self.tracks_extendable:
            if tracklet.start_frame + len(tracklet.bboxes) + \
                self.window_size - tracklet.ttl >= self.frame_num:
                tracks_extendable_updated.append(tracklet)
            # For batch/offline.
            # elif tracklet.max_score >= self.max_det_confidence and tracklet.count >= self.t_min:
            #     # removed.
            #     tracks_finished.append(track)
        self.tracks_extendable = tracks_extendable_updated

        new_dets = [dets[idx] for idx in set(range(len(dets))).difference(set(det_ids))]
        dets_for_new = []

        for det in new_dets:
            finished = False
            # go backwards and track visually
            boxes = []
            vis_tracker = VisTracker(self.tracker_type, det.bbox, frame, \
                self.keep_upper_height_ratio)

            for f in reversed(self.__frame_buffer[:-1]):
                ok, bbox = vis_tracker.update(f)
                if not ok:
                    # can not go further back as the visual tracker failed
                    break
                boxes.append(bbox)

                # sorting is not really necessary but helps to avoid different behaviour for
                # different orderings preferring longer tracks for extension seems intuitive, 
                # LAP solving might be better
                for track in sorted(self.tracks_extendable, key=lambda x: len(x.bboxes), \
                    reverse=True):

                    offset = track.start_frame + len(track.bboxes) + len(boxes) - self.frame_num
                    # association not optimal (LAP solving might be better)
                    # association is performed at the same frame, not adjacent ones
                    if 1 <= offset <= self.window_size - track.ttl and \
                        iou(track.bboxes[-offset], bbox) >= self.iou_threshold:
                        if offset > 1:
                            # remove existing visually tracked boxes behind the matching frame
                            track.bboxes = track.bboxes[:-offset+1]
                        track.bboxes += list(reversed(boxes))[1:]
                        track.bboxes.append(det.bbox)
                        track.max_score = max(track.max_score, det.confidence)
                        track.ttl = self.window_size
                        track.visual_tracker = None

                        self.tracks_extendable.remove(track)
                        # for batch/offline
                        # if track in tracks_finished:
                        #     del tracks_finished[tracks_finished.index(track)]
                        updated_tracks.append(track)

                        finished = True
                        break
                if finished:
                    break
            if not finished:
                dets_for_new.append(det)

        # create new tracks
        new_tracks = [self.__new_tracklet(det) for det in dets_for_new]
        tracks_active = []
        for track in updated_tracks + new_tracks:
            if track.ttl == 0:
                self.tracks_extendable.append(track)
            else:
                tracks_active.append(track)

        self.tracks_active = tracks_active
        self.frame_num += 1

        return tracks_active

class VIOUOnlineTracker(Operator):
    def __init__(self, min_conf = 0.4, iou_threshold=0.5, w=1, tracker='NONE', kuh_ratio=1.0):
        self.tracker = VIOUTracker(
            min_det_confidence = min_conf, 
            iou_threshold = iou_threshold,
            window_size = w, 
            tracker_type= tracker,  
            keep_upper_height_ratio= kuh_ratio 
        )
        super().__init__()

    def process(self, tables):
        frame = tables[fields.DATA_FRAME]
        detections = tables[fields.DATA_OBJECT_DETECTION]
        tracklets = self.tracker.update(frame, detections)
        tables[fields.DATA_OBJECT_TRACK] = [viou_tracklet_to_result(t) for t in tracklets]
        self.collector.emit(tables)
    
class VIOUBatchTracker(Operator):
    def __init__(self, max_conf=0.5, t_min=4, result_only=True, min_conf=0.4, 
            iou_threshold=0.5, w=1, tracker='NONE', kuh_ratio=1.0):
        self.__max_det_confidence = max_conf
        self.__t_min = t_min
        self.__result_only = result_only
        self.tracker =  VIOUTracker(
            min_det_confidence = min_conf, 
            iou_threshold = iou_threshold,
            window_size = w, 
            tracker_type= tracker,  
            keep_upper_height_ratio= kuh_ratio 
        )
        self.max_tracklets = OrderedDict()
        self.track_results = []
        self.buffered_tables = []
        super().__init__()
    
    def process(self, tables):
        frame = tables[fields.DATA_FRAME]
        detections = tables[fields.DATA_OBJECT_DETECTION]
        tracklets = self.tracker.update(frame, detections)
        self.track_results.append(tracklets)
        for track in tracklets:
            self.max_tracklets[track.uid] = track
        if not self.__result_only:
            self.buffered_tables.append(tables)

    def cleanup(self):
        keep_set = set()
        for uid, tracklet in self.max_tracklets.items():
            if tracklet.max_score >= self.__max_det_confidence and \
                len(tracklet.bboxes) >= self.__t_min:
                keep_set.add(uid)
        for idx, frame_result in enumerate(self.track_results):
            tables = self.buffered_tables[idx] if not self.__result_only else {}
            tables[fields.DATA_OBJECT_TRACK] = [viou_tracklet_to_result(i) for i in frame_result if i.uid in keep_set]
            self.collector.emit(tables)
            