model:
  name: 'osnet_x1_0'
  pretrained: True
  load_weights: ../storage/models/reid/osnet_x1_0_imagenet.pth

data:
  root: '../storage/dataset/MOT17Det/'
  type: 'image'
  sources: ['mot17det']
  targets: ['mot17det']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/osnet_x1_0_mot17det_softmax_rx_noexc'

mot:
  vis_threshold: 0.3
  exclude_sequences: []

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 1
  batch_size: 64
  fixbase_epoch: 0
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [60]

test:
  batch_size: 64
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False